@startuml
interface DataReader {
    read(DataSource)
}
interface DataWriter {
    write()
}
class CsvDataReader {
    read(DataSource)
}

class DataSource {
    String dataPath
    String dataType
}
@enduml