spring:
  profiles:
    include: prod
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  server:
    tomcat:
      uri-encoding: UTF-8
  # program argument로 job.name이 설정되지 않으면 아무 배치도 실행하지 않는다
  # --jab.name=<jobname> <parameter> 형식으로 사용
  batch:
    job:
      names: ${job.name:NONE}
---
spring:
  profiles: h2
  datasource:
#    schema: classpath*:db/${database}/schema.sql
#    data: classpath*:db/${database}/data.sql
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mustache:
    cache: false
    prefix: file:src/main/resources/templates/
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/addup?useSSL=true&verifyServerCertificate=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mustache:
    cache: false
    prefix: file:src/main/resources/templates/